//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEAppWS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fxcebas0519:8080/DEWebService/DataEntryQABL.asmx")]
        public string DEAppWS_localhost_DataEntryQABL {
            get {
                return ((string)(this["DEAppWS_localhost_DataEntryQABL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fxcebas0519:8080/DEWebService/VirtualMailRoomBatchSolutionBL.asmx")]
        public string DEAppWS_VirtualMailRoomBatchSolutionBL_VirtualMailRoomBatchSolutionBL {
            get {
                return ((string)(this["DEAppWS_VirtualMailRoomBatchSolutionBL_VirtualMailRoomBatchSolutionBL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fxcebas0519:8080/DEWebService/UserLoginBL.asmx")]
        public string DEAppWS_UserLoginBL_UserLoginBL {
            get {
                return ((string)(this["DEAppWS_UserLoginBL_UserLoginBL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fxcebas0519:8080/DEWebService/ClientSCACValidationBL.asmx")]
        public string DEAppWS_ClientSCACValidationBL_ClientSCACValidationBL {
            get {
                return ((string)(this["DEAppWS_ClientSCACValidationBL_ClientSCACValidationBL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/DEWebService/VendorInfoBL.asmx")]
        public string DEAppWS_VendorInfoBL_VendorInfoBL {
            get {
                return ((string)(this["DEAppWS_VendorInfoBL_VendorInfoBL"]));
            }
        }
    }
}
